[workspace]
resolver = "2"
members = [
    "crates/dygma-layer-switcher",
    "crates/common",
    "crates/platforms/windows",
]

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
