[package]
name = "macintosh"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Wilding <mbwilding@gmail.com>"]

[dependencies]
common = { path = "../../common" }
anyhow = "1.0"
tracing = { version = "0.1", features = ["log"] }
cocoa = "0.25"
core-graphics = "0.23"
objc = "0.2"
