name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  APT_PACKAGES: libatk1.0-dev libpango1.0-dev libgtk-3-dev libudev-dev libxdo-dev

jobs:
  checks:
    name: "Checks"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          # - aarch64-pc-windows-gnu
          # - x86_64-apple-darwin
          # - x86_64-unknown-linux-gnu

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
          target: ${{ matrix.target }}

      - name: "Dependencies"
        run: sudo apt-get install -y ${{ env.APT_PACKAGES }}

      - name: "Format"
        run: cargo fmt -- --check

      - name: "Clippy"
        run: cargo clippy --target ${{ matrix.target }} -- -D warnings
